### ISSUE TITLE
Ansible role, AttributeError: 'Settings' object has no attribute 'TIAAS_RETAIN_CONTACT_REQUIRE_CONSEN

### ISSUE THREAD

**Issue by Dirowa** [galaxyproject/ansible-tiaas2#21]
hi @hexylena 

I was testing the Tiaas server of Avans Galaxy and i got an error. Server Error (500)

After checking the logfiles of journalctl I got the following.

```
Nov 14 13:25:08 galaxy.atgm.avans.nl run.sh[944718]: [pid: 944718|app: 0|req: 14/14] 145.48.76.238 () {60 vars in 1651 bytes} [Mon Nov 14 13:25:08 2022] GET /tiaas/ =>
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]: ERROR | log: Internal Server Error: /tiaas/
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]: Traceback (most recent call last):
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     response = get_response(request)
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/code/./training/views.py", line 83, in about
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     return render(request, "training/about.html")
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     content = loader.render_to_string(template_name, context, request, using=using)
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     return template.render(context, request)
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     return self.template.render(context)
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     with context.bind_template(self):
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     return next(self.gen)
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/template/context.py", line 244, in bind_template
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     updates.update(processor(self.request))
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/code/./training/context_processors.py", line 16, in settings
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     'TIAAS_RETAIN_CONTACT_REQUIRE_CONSENT': app_settings.TIAAS_RETAIN_CONTACT_REQUIRE_CONSENT,
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:   File "/srv/tiaas/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]:     val = getattr(self._wrapped, name)
Nov 14 13:44:32 galaxy.atgm.avans.nl run.sh[944718]: AttributeError: 'Settings' object has no attribute 'TIAAS_RETAIN_CONTACT_REQUIRE_CONSENT'

```
Currently running version 0.0.9 from the ansible repo.
Is this an internal bug or do you know where to look at?

**Comment by hexylena** [comment]
heh, no, that's my fault. we need to update the role to 2.1.0 and make some other changes. https://github.com/galaxyproject/ansible-tiaas2#migrating-to-the-new-tiaas if you feel up to making those changes. my bad!!
